services:
  order-app:
    build: ./order-app
    ports:
      - "3000:3000"
    volumes:
      - ./order-app/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=new_password
      - MYSQL_DATABASE=order_app
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=new_password
      - MYSQL_TCP_PORT=3307